version: 0.2
phases:
 install:
   runtime-versions:
     php: 8.x
   commands:
     - curl -s https://getcomposer.org/installer | php
     - mv  composer.phar /usr/local/bin/composer
     - php --version
     - npm install
     - npm run prod
    
 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install
     - composer
     - cp .env.example .env
     - php artisan key:generate
     - php artisan config:cache
     - php artisan route:cache
     - php artisan config:clear
     - php artisan cache:clear
 post_build:
   commands:
     - echo Build completed on `date`
     
artifacts:
  files:
    - '**/*'
  name: Laravel-$(date +%Y-%m-%d)
