version: 0.2
phases:
 install:
   commands:
     - curl -s https://getcomposer.org/installer | php
     - mv  composer.phar /usr/local/bin/composer
     - php --version
     - npm install
     - npm run prod
     - sudo yum -y update
     - sudo yum -y install ruby
     - sudo yum -y install wget
     - cd /home/ec2-user
     - wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
     - sudo chmod +x ./install
     - sudo ./install auto
 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install
     - composer
     - cp .env.example .env
     - php artisan key:generate
     - php artisan config:cache
     - php artisan route:cache
     - php artisan config:clear
     - php artisan cache:clear
 post_build:
   commands:
     - echo Build completed on `date`
     
artifacts:
  files:
    - '**/*'
  name: Laravel-$(date +%Y-%m-%d)
